apiVersion: apps/v1
kind: Deployment
metadata:
  name: db1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db1
  template:
    metadata:
      labels:
        app: db1
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db1.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db1.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.db1.database | quote }}
          volumeMounts:
            - name: db1-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db1-init
          configMap:
            name: db1-init-sql