apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: {{ .Values.pgadmin.service.type }}
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: {{ .Values.pgadmin.service.nodePort }}
